apiVersion: v1
kind: Service
metadata:
  name: flask-devops-showcase
spec:
  selector:
    app: flask-devops-showcase
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
